### PR TITLE
Fix ddf.groupby with scalar group_keys and falsy column slicing

### PR DESCRIPTION
**Pull request by JacobHayes**
When working with some `ddf`s recently containing integer columns, I noticed a couple issues when slicing column `0`, which is "falsy" - depending on the operation, sometimes I would get the wrong column output (eg: `.groupby(...)[0].agg(...)` would return a different column, _if_ `0` wasn't the first) or get a dataframe back instead of a series. These were mostly caused by `if self._slice` checks which should be `if self._slice is None` checks.

While looking into this, I also discovered issues with `ddf.groupby(scalar_value).cov()`. I think this is mostly isolated to `.cov`, but there's a lot of other logic checking or converting `self.by` to a list elsewhere, so harder to say.

The added tests fail when run without the changes, but aren't particularly clear/tidy - any suggestions on a better way (or an existing test)?

- [ ] Closes #xxxx
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

File: dask/dataframe/groupby.py [hunk 1]
```diff
@@ -2119,10 +2122,11 @@ def nunique(self, split_every=None, split_out=1):
     @derived_from(pd.core.groupby.SeriesGroupBy)
     def aggregate(self, arg, split_every=None, split_out=1):
         result = super().aggregate(arg, split_every=split_every, split_out=split_out)
-        if self._slice:
+        if self._slice is not None:
             result = result[self._slice]
 
         if not isinstance(arg, (list, dict)) and isinstance(result, DataFrame):
+            assert len(result.columns) == 1
             result = result[result.columns[0]]
```
Comment (JacobHayes) [inline dask/dataframe/groupby.py:2130]: This bit is extra confusing - before this PR, the output would depend on the column order:
```python
[ins] In [1]: import dask.dataframe as dd
         ...: import pandas as pd

[ins] In [2]: ddf = dd.from_pandas(pd.DataFrame([[0, 1, 2]], columns=[0, 1, 2]), npartitions=1)

[ins] In [3]: ddf.groupby(2)[0].agg("sum").name
Out[3]: 0

[ins] In [4]: ddf.columns = [2, 1, 0]

[ins] In [5]: ddf.groupby(2)[0].agg("sum").name
Out[5]: 1
```

Effectively, the `if self._slice:` would be `False`, but then `if not isinstance(arg, (list, dict)) and isinstance(result, DataFrame)` would be True, and then we'd **filter to the first column**.

I'm not sure under what condition we hit `if not isinstance(arg, ...` when using a single agg func (as we are inside `SeriesGroupBy`), but I think the assumption is that there'd only be 1 column in that DataFrame, so I added the assert. If that's assumption is right, is an `assert` fine (I see a couple others in this file) or should this be a `raise`d exception?

**Review by jrbourbeau — COMMENTED** [review]
Thanks for fixing and adding tests @JacobHayes!

File: dask/dataframe/groupby.py [hunk 2]
```diff
@@ -2119,10 +2122,11 @@ def nunique(self, split_every=None, split_out=1):
     @derived_from(pd.core.groupby.SeriesGroupBy)
     def aggregate(self, arg, split_every=None, split_out=1):
         result = super().aggregate(arg, split_every=split_every, split_out=split_out)
-        if self._slice:
+        if self._slice is not None:
             result = result[self._slice]
 
         if not isinstance(arg, (list, dict)) and isinstance(result, DataFrame):
+            assert len(result.columns) == 1
```
[the remark this answers is not in the document]
Comment (JacobHayes) [reply dask/dataframe/groupby.py:2129]: It was intentional, but I'm not certain it's correct and was trying to reason through it - If we have a single aggregation I _think_ it should only have a single column, but if there _were_ multiple, why is column 0 special?

It did "mask" [my issue](https://github.com/dask/dask/pull/9020#discussion_r864436331) a bit - instead of returning a dataframe with all columns (because the `if self._slice` was skipped - which would also be wrong, but was expected at first glance), I would get the wrong column (because the column named `1` was the 0th column).

File: dask/dataframe/tests/test_groupby.py [hunk 3]
```diff
@@ -2684,3 +2684,41 @@ def test_groupby_iter_fails():
...
+    groupby = ddf.groupby([2])
+    # .agg
+    assert groupby[0].agg("sum").name == 0
+    assert groupby[1].agg("sum").name == 1
+    # .cov
+    assert groupby[0].cov().name == 0
+    assert groupby[1].cov().name == 1
+    # .var
+    assert groupby[0].var().name == 0
+    assert groupby[1].var().name == 1
```
[the remark this answers is not in the document]
Comment (JacobHayes) [reply dask/dataframe/tests/test_groupby.py]: Hmm, I think there's another `.cov` difference:
```
(Pdb) df.groupby([2])[0].cov()
*** TypeError: cov() missing 1 required positional argument: 'other'
(Pdb) ddf.groupby([2])[0].cov().compute()
2
0  0    0.0
Name: 0, dtype: float64
```
Any quick suggestions there or should I open a separate ticket?

**Comment by JacobHayes** [comment]
Tests are broken due to https://github.com/dask/dask/pull/9020#discussion_r867429175 - I think that's a separate `.cov` incompatibility w/ the pandas version. I haven't had time to look in to see if that'd be a quick thing to fix or worth a separate issue (and removing from these tests for now).

File: dask/dataframe/tests/test_groupby.py [hunk 4]
```diff
@@ -2684,3 +2684,43 @@ def test_groupby_iter_fails():
...
+    expected = df.groupby(2).cov()
+    result = ddf.groupby(2).cov()
+    assert_eq(result, expected)
+
+
+@pytest.mark.parametrize(
+    ["op"],
+    [
+        [lambda s: s.agg("sum")],
+        [lambda s: s.cov()],
```
Comment (pavithraes) [inline dask/dataframe/tests/test_groupby.py:2709]: I think we don't need to check for `cov()` here. By definition, we take `cov` between two columns (that's why we get the [`cov() missing 1 required positional argument: 'other'`](https://github.com/dask/dask/runs/6338467120?check_suite_focus=true#step:6:21599) error), which is covered by your previous test. :)

```suggestion
```

**Comment by JacobHayes** [comment]
Looks like there's a [difference in 3.8](https://github.com/dask/dask/actions/runs/2679361066) where pandas returns an int64 dtype while dask returns a float64 (tests also failed on 3.9/macos, but I think that was just a flake). I rebased and will see if I can debug, but seems like it might not be directly related to these changes (aside from new tests).

**Comment by JacobHayes** [comment]
Ok, I think this is because `pandas==1.2.5` is installed for 3.8 (`pandas==1.3.5` is used for 3.9), which doesn't use the `int64` type.

For now, I changed my tests to explicitly say `float64`.

**Comment by JacobHayes** [comment]
I think the two failing tests in the latest commit are flakes, or at least unrelated:
- `dask/array/tests/test_reductions.py::test_reductions_2D[f4]`
- `dask/tests/test_distributed.py::test_blockwise_dataframe_io[True-None-hdf]`

I think all of my commits have had flakes (ignoring the true failures) so I won't commit again just for a rerun. Could someone "rerun failed jobs"? 🙏
