### ISSUE TITLE
dask.fft does not work with cupy arrays

### ISSUE THREAD

**Issue by izaid** [dask/dask#6118]
```
import numpy as np

import cupy as cp

import dask.array as da

x = cp.random.randn(128, 128)
x = da.from_array(x)

da.fft.fft2(x)
```

Similar to my last issue. It may be that I've mistakenly assumed `dask` has support for `cupy`, in which case my apologies. I've seen examples with `dask` and `cupy`, but do not know how extensive that is.

**Comment by mrocklin** [comment]
@izaid thanks for raising.  cc @pentschev and @quasiben from NVIDIA in case they have time to test this out.

**Comment by pentschev** [comment]
For completeness, this is the error:

```python
Exception ignored in: <bound method PlanNd.__del__ of <cupy.cuda.cufft.PlanNd object at 0x7f22d8142c80>>
Traceback (most recent call last):
  File "cupy/cuda/cufft.pyx", line 277, in cupy.cuda.cufft.PlanNd.__del__
AttributeError: 'PlanNd' object has no attribute 'plan'
```

I'm not totally sure what's missing here, perhaps we need to do some handling of plans for CuPy, that would need to be investigated. For sure at least https://github.com/dask/dask/blob/71113eacbf83437f59984d053c10e52f6ce97f70/dask/array/fft.py#L173 would have to be replaced with https://github.com/dask/dask/blob/71113eacbf83437f59984d053c10e52f6ce97f70/dask/array/utils.py#L313, but I'm not sure if that's all that's necessary, I guess not.

Unfortunately, I won't have time for any further investigation until at least mid/late May.

**Comment by pentschev** [comment]
Also linked this to our `__array_function__` issue tracker in #4731 .

**Comment by mrocklin** [comment]
> Unfortunately, I won't have time for any further investigation until at least mid/late May.

Sure, I'm certain that all of the UCX issues will be ironed out before then ;)

**Comment by leofang** [comment]
For some reason my browser opened up this issue to me 🧐 @izaid @pentschev Could you please check if the execution runs correctly, i.e. the result of `da.fft.fft2(x)` is correct? Note that the error happens at `__del__`, which in my experience is related to object lifetime not being properly handled in a given context (CUDA's or other libraries').

**Comment by quasiben** [comment]
Things do work but an odd exception is raised?

```python
In [21]: import numpy as np
    ...:
    ...: import cupy as cp
    ...:
    ...: import dask.array as da
    ...:
    ...: y = cp.random.randn(128, 128)
    ...: x = da.from_array(y)
    ...:
    ...: arr = da.fft.fft2(x)
Exception ignored in: <bound method PlanNd.__del__ of <cupy.cuda.cufft.PlanNd object at 0x7f3de3178d60>>
Traceback (most recent call last):
  File "cupy/cuda/cufft.pyx", line 277, in cupy.cuda.cufft.PlanNd.__del__
AttributeError: 'PlanNd' object has no attribute 'plan'

In [22]: da.utils.assert_eq(arr.compute(), cp.fft.fft2(y))
Out[22]: True
``` 

I am guessing the exception happens during meta construction...

This is with cupy version 7.6.0

**Comment by pentschev** [comment]
I tested this with CuPy 8.0.0b5 and it works, but still fails with 7.7.0. Given there has been a lot of changes for CuPy 8 on the cuFFT front, I think it's unlikely that those changes will be backported to CuPy 7.

@izaid FYI, CuPy 8 is scheduled for release in late September, so by then this should be no problem anymore, if you can't wait you may considering building it from source to get past this issue.

**Comment by izaid** [comment]
@pentschev Cheers, thanks for that! Looking forward to giving this a shot with CuPy 8.

**Comment by leofang** [comment]
I verified this works with CuPy v8 and Dask v2.30.

**Comment by mrocklin** [comment]
I'm glad to hear it.  Thanks for reporting @leofang .

Closing.

**Comment by makslevental** [comment]
I'm confused about how this should work? Running the initial code does indeed produce an FFT but from what I can tell (by watching `nvidia-smi`) dask does not use my GPUs when I run in this way. Is that correct? Is there a way to get dask to perform these FFTs on gpu workers?

**Comment by quasiben** [comment]
@makslevental -- I would recommend opening up a new issue with a minimal reproducer if you have a problem here.   Generally, the way this works is through is with [NEP-18 ](https://numpy.org/neps/nep-0018-array-function-protocol.html), a protocol to dispatch to other libraries from NumPy


```python
In [1]: import cupy

In [2]: import numpy as np

In [3]: arr = cupy.random.randn(128, 128)

In [4]: res = np.fft.fft(arr)

In [5]: type(res)
Out[5]: cupy.core.core.ndarray
```

**Comment by makslevental** [comment]
@quasiben thanks for the tip. will do if I can't track it down.
