### ISSUE TITLE
`aiobotocore` releated test failures

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8335]
Some of our tests have started failing with

```
AttributeError: module 'aiobotocore' has no attribute 'AioSession'
```

due to the new `aiobotocore` 2.0.0 release. Working on a fix now, just wanted to surface this for others

**Comment by jrbourbeau** [comment]
Turns out this was already fixed upstream in `s3fs` but, for some reason I'm still not sure of, we've been pulling in an older version of `s3fs` in CI (specifically `s3fs==0.6.0`). I've proposed we add an `s3fs` version constraint to our CI environments over in https://github.com/dask/dask/pull/8336. For an example of the current test failures see the CI builds in https://github.com/dask/dask/pull/8337

**Comment by jsignell** [comment]
Do we want to unpin at some point or are we happy to just close this?

**Comment by rileyhun** [comment]
I'm dealing with this issue as well and I believe I'm using the latest version of `s3fs`. Is there a fix for this?

**Comment by jrbourbeau** [comment]
I'm checking over in https://github.com/jrbourbeau/dask/tree/unpin-s3fs whether we can unpin `s3fs` today or not

**Comment by abhishek815** [comment]
I believe the issue is occurring again. I was not receiving this error previously but the issue is occurring again as of a few hours ago @ian-r-rose.

**Comment by ian-r-rose** [comment]
Do you have a link to a failure in the `dask/dask` test suite? `aiobotocore` has a history of releasing API breaking changes, but this issue meant to track its usage in the test suite here.

**Comment by abhishek815** [comment]
No I do not, sorry this wasn't test related. 
```
AttributeError: module 'aiobotocore' has no attribute 'AioSession'
```
This issue is replicated on both pandas and dask when I read parquet_files from s3. I've posted a separate issue on [s3fs's github repo](https://github.com/fsspec/s3fs/issues/642)

**Comment by ian-r-rose** [comment]
Looks like you've resolved it in s3fs, glad you got it working @abhishek815 !

**Comment by openSourcerer9000** [comment]
Still getting this error when running cell 5 of this: https://nbviewer.org/github/NOAA-OWP/AORC-jupyter-notebooks/blob/master/jupyter_notebooks/AORC_Zarr_notebook.ipynb
