### ISSUE TITLE
Numpy dtype fails to pickle "'_DTypeMeta' has no attribute '_abstract'"

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7170]
I am having trouble repeatably reproducing this locally, but with numpy 1.20 and dask/distributed master I am seeing failures in CI to pickle numpy.dtypes. I am not quite sure if this is related to https://github.com/numpy/numpy/issues/16692 or not

For instance: https://github.com/dask/dask/pull/6896/checks?check_run_id=1832018385 contains:

```python-traceback
______________________ test_futures_to_delayed_dataframe _______________________
[gw1] darwin -- Python 3.8.6 /Users/runner/miniconda3/envs/test-environment/bin/python

c = <Client: 'tcp://127.0.0.1:50526' processes=2 threads=2, memory=30.06 GB>

    def test_futures_to_delayed_dataframe(c):
        pd = pytest.importorskip("pandas")
        dd = pytest.importorskip("dask.dataframe")
        df = pd.DataFrame({"x": [1, 2, 3]})
    
        futures = c.scatter([df, df])
>       ddf = dd.from_delayed(futures)

dask/tests/test_distributed.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/io/io.py:593: in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
dask/base.py:281: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:563: in compute
    results = schedule(dsk, keys, **kwargs)
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/client.py:2684: in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/client.py:1993: in gather
    return self.sync(
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/client.py:839: in sync
    return sync(
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/utils.py:340: in sync
    raise exc.with_traceback(tb)
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/utils.py:324: in f
    result[0] = yield future
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/tornado/gen.py:762: in run
    value = future.result()
../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/client.py:1858: in _gather
    raise exception.with_traceback(traceback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   return pickle.loads(x)
E   AttributeError: type object '_DTypeMeta' has no attribute '_abstract'

../../../miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/protocol/pickle.py:75: AttributeError
---------------------------- Captured stderr setup -----------------------------
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://127.0.0.1:50526
distributed.scheduler - INFO -   dashboard at:            127.0.0.1:8787
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:50528
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:50528
distributed.worker - INFO -          dashboard at:            127.0.0.1:50530
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:50526
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   15.03 GB
distributed.worker - INFO -       Local Directory: /Users/runner/work/dask/dask/_test_worker-86b5d0e8-bd7b-41a8-8334-973c85d24984/dask-worker-space/worker-20mc10c6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:50529
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:50529
distributed.worker - INFO -          dashboard at:            127.0.0.1:50531
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:50526
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   15.03 GB
distributed.worker - INFO -       Local Directory: /Users/runner/work/dask/dask/_test_worker-ec84ae08-7a8b-4d73-b1c0-453815a4fe2d/dask-worker-space/worker-soyylpls
distributed.worker - INFO - -------------------------------------------------
distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:50528', name: tcp://127.0.0.1:50528, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:50528
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:50526
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register worker <Worker 'tcp://127.0.0.1:50529', name: tcp://127.0.0.1:50529, memory: 0, processing: 0>
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:50529
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:      tcp://127.0.0.1:50526
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Receive client connection: Client-23332ef2-6702-11eb-8b01-005056802233
distributed.core - INFO - Starting established connection
----------------------------- Captured stderr call -----------------------------
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\xc1\x05\x00\x00\x00\x00\x00\x00\x8c\ndask.utils\x94\x8c\x08Dispatch\x94\x93\x94)\x81\x94}\x94(\x8c\x07_lookup\x94}\x94(\x8c\x12pandas.core.series\x94\x8c\x06Series\x94\x93\x94\x8c\x14dask.dataframe.utils\x94\x8c\x10make_meta_pandas\x94\x93\x94\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94h\x0c\x8c\x18pandas.core.indexes.base\x94\x8c\x05Index\x94\x93\x94h\n\x8c\x0fmake_meta_index\x94\x93\x94\x8c\x08builtins\x94\x8c\x06object\x94\x93\x94h\n\x8c\x10make_meta_object\x94\x93\x94\x8c\x13dask.dataframe.core\x94h\x08\x93\x94h\x19\x8c\x1cpandas.core.indexes.category\x94\x8c\x10CategoricalIndex\x94\x93\x94h\x14h\x15\x8c\x04dict\x94\x93\x94h\x19\x8c\x1bpandas.core.indexes.numeric\x94\x8c\nInt64Index\x94\x93\x94h\x14\x8c\x05numpy\x94\x8c\x05int64\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94h\x14h\x1ah\x0e\x93\x94h\x19h$\x8c\x07ndarray\x94\x93\x94h\x19h\x15\x8c\x04type\x94\x93\x94h\x19\x8c\x1dpandas.core.indexes.datetimes\x94\x8c\rDatetimeIndex\x94\x93\x94h\x14h\x1ah\x11\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timestamps\x94\x8c\tTimestamp\x94\x93\x94h\x19h!\x8c\x0cFloat64Index\x94\x93\x94h\x14h$\x8c\x08recarray\x94\x93\x94h\x19h\x15\x8c\x04list\x94\x93\x94h\x19h\x15\x8c\x05tuple\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.multi\x94\x8c\nMultiIndex\x94\x93\x94h\x14h\x15\x8c\x03str\x94\x93\x94h\x19h\x1a\x8c\x06Scalar\x94\x93\x94h\x19h$\x8c\x07float64\x94\x93\x94h\x19h$\x8c\x05bool_\x94\x93\x94h\x19h\x15\x8c\x03int\x94\x93\x94h\x19h\x15\x8c\x04bool\x94\x93\x94h\x19h\x15\x8c\x05float\x94\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timedeltas\x94\x8c\tTimedelta\x94\x93\x94h\x19h$\x8c\x04str_\x94\x93\x94h\x19\x8c\x17cloudpickle.cloudpickle\x94\x8c\x14_make_skeleton_class\x94\x93\x94(hV(h.\x8c\n_DTypeMeta\x94h.\x85\x94}\x94\x8c 159ec8cc5ff94dc78ce596ecc953ca84\x94Nt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x0f_class_setstate\x94\x93\x94h\\}\x94(\x8c\x08__init__\x94\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94h\\ha\x86\x94R\x94\x8c\x07__new__\x94hdh\\\x8c\x07__new__\x94\x86\x94R\x94\x8c\t_abstract\x94hdh\\hk\x86\x94R\x94\x8c\x04type\x94hdh\\hn\x86\x94R\x94\x8c\x0b_parametric\x94hdh\\hq\x86\x94R\x94\x8c\x07__doc__\x94\x8c;Preliminary NumPy API: The Type of NumPy DTypes (metaclass)\x94u}\x94\x86\x94\x86R0\x8c\x0cdtype[bool_]\x94h$\x8c\x05dtype\x94\x93\x94\x85\x94}\x94\x8c 92dfbada8b7040e9903c51b862d870a4\x94Nt\x94R\x94h_h\x7f}\x94hghdh\x7f\x8c\x07__new__\x94\x86\x94R\x94s}\x94\x86\x94\x86R0h\x19h.N\x85\x94R\x94h\x19u\x8c\x05_lazy\x94}\x94\x8c\x04cudf\x94\x8c\x17dask.dataframe.backends\x94\x8c\x0e_register_cudf\x94\x93\x94s\x8c\x08__name__\x94\x8c\tmake_meta\x94ub.'
Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/worker.py", line 3340, in loads_function
    result = cache_loads[bytes_object]
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/utils.py", line 1514, in __getitem__
    value = super().__getitem__(key)
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95\xc1\x05\x00\x00\x00\x00\x00\x00\x8c\ndask.utils\x94\x8c\x08Dispatch\x94\x93\x94)\x81\x94}\x94(\x8c\x07_lookup\x94}\x94(\x8c\x12pandas.core.series\x94\x8c\x06Series\x94\x93\x94\x8c\x14dask.dataframe.utils\x94\x8c\x10make_meta_pandas\x94\x93\x94\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94h\x0c\x8c\x18pandas.core.indexes.base\x94\x8c\x05Index\x94\x93\x94h\n\x8c\x0fmake_meta_index\x94\x93\x94\x8c\x08builtins\x94\x8c\x06object\x94\x93\x94h\n\x8c\x10make_meta_object\x94\x93\x94\x8c\x13dask.dataframe.core\x94h\x08\x93\x94h\x19\x8c\x1cpandas.core.indexes.category\x94\x8c\x10CategoricalIndex\x94\x93\x94h\x14h\x15\x8c\x04dict\x94\x93\x94h\x19\x8c\x1bpandas.core.indexes.numeric\x94\x8c\nInt64Index\x94\x93\x94h\x14\x8c\x05numpy\x94\x8c\x05int64\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94h\x14h\x1ah\x0e\x93\x94h\x19h$\x8c\x07ndarray\x94\x93\x94h\x19h\x15\x8c\x04type\x94\x93\x94h\x19\x8c\x1dpandas.core.indexes.datetimes\x94\x8c\rDatetimeIndex\x94\x93\x94h\x14h\x1ah\x11\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timestamps\x94\x8c\tTimestamp\x94\x93\x94h\x19h!\x8c\x0cFloat64Index\x94\x93\x94h\x14h$\x8c\x08recarray\x94\x93\x94h\x19h\x15\x8c\x04list\x94\x93\x94h\x19h\x15\x8c\x05tuple\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.multi\x94\x8c\nMultiIndex\x94\x93\x94h\x14h\x15\x8c\x03str\x94\x93\x94h\x19h\x1a\x8c\x06Scalar\x94\x93\x94h\x19h$\x8c\x07float64\x94\x93\x94h\x19h$\x8c\x05bool_\x94\x93\x94h\x19h\x15\x8c\x03int\x94\x93\x94h\x19h\x15\x8c\x04bool\x94\x93\x94h\x19h\x15\x8c\x05float\x94\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timedeltas\x94\x8c\tTimedelta\x94\x93\x94h\x19h$\x8c\x04str_\x94\x93\x94h\x19\x8c\x17cloudpickle.cloudpickle\x94\x8c\x14_make_skeleton_class\x94\x93\x94(hV(h.\x8c\n_DTypeMeta\x94h.\x85\x94}\x94\x8c 159ec8cc5ff94dc78ce596ecc953ca84\x94Nt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x0f_class_setstate\x94\x93\x94h\\}\x94(\x8c\x08__init__\x94\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94h\\ha\x86\x94R\x94\x8c\x07__new__\x94hdh\\\x8c\x07__new__\x94\x86\x94R\x94\x8c\t_abstract\x94hdh\\hk\x86\x94R\x94\x8c\x04type\x94hdh\\hn\x86\x94R\x94\x8c\x0b_parametric\x94hdh\\hq\x86\x94R\x94\x8c\x07__doc__\x94\x8c;Preliminary NumPy API: The Type of NumPy DTypes (metaclass)\x94u}\x94\x86\x94\x86R0\x8c\x0cdtype[bool_]\x94h$\x8c\x05dtype\x94\x93\x94\x85\x94}\x94\x8c 92dfbada8b7040e9903c51b862d870a4\x94Nt\x94R\x94h_h\x7f}\x94hghdh\x7f\x8c\x07__new__\x94\x86\x94R\x94s}\x94\x86\x94\x86R0h\x19h.N\x85\x94R\x94h\x19u\x8c\x05_lazy\x94}\x94\x8c\x04cudf\x94\x8c\x17dask.dataframe.backends\x94\x8c\x0e_register_cudf\x94\x93\x94s\x8c\x08__name__\x94\x8c\tmake_meta\x94ub.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 75, in loads
    return pickle.loads(x)
AttributeError: type object '_DTypeMeta' has no attribute '_abstract'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/worker.py", line 3340, in loads_function
    result = cache_loads[bytes_object]
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/utils.py", line 1514, in __getitem__
    value = super().__getitem__(key)
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95\xc1\x05\x00\x00\x00\x00\x00\x00\x8c\ndask.utils\x94\x8c\x08Dispatch\x94\x93\x94)\x81\x94}\x94(\x8c\x07_lookup\x94}\x94(\x8c\x12pandas.core.series\x94\x8c\x06Series\x94\x93\x94\x8c\x14dask.dataframe.utils\x94\x8c\x10make_meta_pandas\x94\x93\x94\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94h\x0c\x8c\x18pandas.core.indexes.base\x94\x8c\x05Index\x94\x93\x94h\n\x8c\x0fmake_meta_index\x94\x93\x94\x8c\x08builtins\x94\x8c\x06object\x94\x93\x94h\n\x8c\x10make_meta_object\x94\x93\x94\x8c\x13dask.dataframe.core\x94h\x08\x93\x94h\x19\x8c\x1cpandas.core.indexes.category\x94\x8c\x10CategoricalIndex\x94\x93\x94h\x14h\x15\x8c\x04dict\x94\x93\x94h\x19\x8c\x1bpandas.core.indexes.numeric\x94\x8c\nInt64Index\x94\x93\x94h\x14\x8c\x05numpy\x94\x8c\x05int64\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.range\x94\x8c\nRangeIndex\x94\x93\x94h\x14h\x1ah\x0e\x93\x94h\x19h$\x8c\x07ndarray\x94\x93\x94h\x19h\x15\x8c\x04type\x94\x93\x94h\x19\x8c\x1dpandas.core.indexes.datetimes\x94\x8c\rDatetimeIndex\x94\x93\x94h\x14h\x1ah\x11\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timestamps\x94\x8c\tTimestamp\x94\x93\x94h\x19h!\x8c\x0cFloat64Index\x94\x93\x94h\x14h$\x8c\x08recarray\x94\x93\x94h\x19h\x15\x8c\x04list\x94\x93\x94h\x19h\x15\x8c\x05tuple\x94\x93\x94h\x19\x8c\x19pandas.core.indexes.multi\x94\x8c\nMultiIndex\x94\x93\x94h\x14h\x15\x8c\x03str\x94\x93\x94h\x19h\x1a\x8c\x06Scalar\x94\x93\x94h\x19h$\x8c\x07float64\x94\x93\x94h\x19h$\x8c\x05bool_\x94\x93\x94h\x19h\x15\x8c\x03int\x94\x93\x94h\x19h\x15\x8c\x04bool\x94\x93\x94h\x19h\x15\x8c\x05float\x94\x93\x94h\x19\x8c\x1epandas._libs.tslibs.timedeltas\x94\x8c\tTimedelta\x94\x93\x94h\x19h$\x8c\x04str_\x94\x93\x94h\x19\x8c\x17cloudpickle.cloudpickle\x94\x8c\x14_make_skeleton_class\x94\x93\x94(hV(h.\x8c\n_DTypeMeta\x94h.\x85\x94}\x94\x8c 159ec8cc5ff94dc78ce596ecc953ca84\x94Nt\x94R\x94\x8c\x1ccloudpickle.cloudpickle_fast\x94\x8c\x0f_class_setstate\x94\x93\x94h\\}\x94(\x8c\x08__init__\x94\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94h\\ha\x86\x94R\x94\x8c\x07__new__\x94hdh\\\x8c\x07__new__\x94\x86\x94R\x94\x8c\t_abstract\x94hdh\\hk\x86\x94R\x94\x8c\x04type\x94hdh\\hn\x86\x94R\x94\x8c\x0b_parametric\x94hdh\\hq\x86\x94R\x94\x8c\x07__doc__\x94\x8c;Preliminary NumPy API: The Type of NumPy DTypes (metaclass)\x94u}\x94\x86\x94\x86R0\x8c\x0cdtype[bool_]\x94h$\x8c\x05dtype\x94\x93\x94\x85\x94}\x94\x8c 92dfbada8b7040e9903c51b862d870a4\x94Nt\x94R\x94h_h\x7f}\x94hghdh\x7f\x8c\x07__new__\x94\x86\x94R\x94s}\x94\x86\x94\x86R0h\x19h.N\x85\x94R\x94h\x19u\x8c\x05_lazy\x94}\x94\x8c\x04cudf\x94\x8c\x17dask.dataframe.backends\x94\x8c\x0e_register_cudf\x94\x93\x94s\x8c\x08__name__\x94\x8c\tmake_meta\x94ub.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/worker.py", line 2502, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*ts.runspec)
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/worker.py", line 3351, in _deserialize
    function = loads_function(function)
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/worker.py", line 3342, in loads_function
    result = pickle.loads(bytes_object)
  File "/Users/runner/miniconda3/envs/test-environment/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 75, in loads
    return pickle.loads(x)
AttributeError: type object '_DTypeMeta' has no attribute '_abstract'
```

**Comment by seberg** [comment]
Sorry about this, I had thought that fixing this would be deep trouble, so it never happened. But it seems there is a simple solution, which should be in 1.20.1, so hopefully, you can just be patient for a few days and not worry about it.

**Comment by jsignell** [comment]
Oh great! Thanks so much :)

**Comment by seberg** [comment]
Posted that under the assumption that the numpy `type(dtype)` pickle issue is at the core of this. I really hope there is not more to this :/!

**Comment by bnavigator** [comment]
FYI, the skip in https://github.com/dask/dask/blob/9426a823bc12034031f3c90e74c7be8f4cb94ca6/dask/tests/test_distributed.py#L72 introduced in #6896 assumes, that numpy and dask-array are importable, which is not necessarily the case. Numpy and dask.array should be kept optional.

**Comment by jsignell** [comment]
Thanks for bringing that up @bnavigator! I'll put up a fix.

**Comment by bnavigator** [comment]
Oh, one more thing: there are two more tests in test_distributed, which need dask.dataframe, and thus numpy. We have to skip those for python 3.6 too, because we now have NumPy 1.20 in openSUSE Tumbleweed which dropped Python 3.6:

https://build.opensuse.org/package/view_file/devel:languages:python:numeric/python-dask/python-dask.spec?expand=1
effective call: `pytest-3.6 -k "not ( ... or (test_distributed and test_to_hdf))"` which skips these two: https://github.com/dask/dask/blob/9426a823bc12034031f3c90e74c7be8f4cb94ca6/dask/tests/test_distributed.py#L121-L142

**Comment by jsignell** [comment]
I think I am missing something. Can't you just have a different version of numpy with python 3.6?

**Comment by bnavigator** [comment]
Unfortunately no, not without a lot of work. But that is a different topic. We only have Python 3.6 in openSUSE Tumbleweed as a legacy.

**Comment by jsignell** [comment]
> Unfortunately no

:( 

I don't think it's appropriate to include that kind of skip in dask since we do test with python 3.6 and an older version of numpy. Dask doesn't want to be in the business of dependency management.

**Comment by bnavigator** [comment]
Sure, it is just to let you know, that those distributed tests fail if you don't have dataframe, which should be optional.

**Comment by jsignell** [comment]
Oh! I misunderstood. Yes I will add a pandas skip in there.

**Comment by jsignell** [comment]
Can you see if https://github.com/dask/dask/pull/7247 resolves everything you mentioned?

**Comment by bnavigator** [comment]
Yes, thank you!

**Comment by jsignell** [comment]
I just got rid of the skip in #7441 and everything is as expected so I think the upstream fix does what we needed :)
