### PR TITLE
Allow `pyarrow` CI to fail

### PR DESCRIPTION
**Pull request by jrbourbeau**
This is a follow-up to https://github.com/dask/dask/pull/10097. Now that `pandas=2.0` is out we can now run our `dataframe.convert-string=True` CI build without `continue-on-error: ${{ matrix.extra == 'pyarrow' }}`. Previously we allowed failures in this build because (prior to the `pandas=2.0` release) we needed to use the nightly `pandas` wheel and would pull encounter unrelated failures due to, for example, some non-`pyarrow` related deprecations. 

cc @j-bennet @phofl for visibility

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Okay, so the `test_to_numeric_on_dask_dataframe_series` failure is legitimate and I just pushed a commit with a fix. `test_roundtrip_decimal_dtype` is now passing, so I've removed the `xfail` marker. The remaining `AttributeError: 'ArrowStringArray' object has no attribute 'tobytes'` failures are due to https://github.com/dask/partd/pull/64 not being included in a `partd` release. I'll push out a `partd` release later today (xref https://github.com/dask/partd/issues/66) and then will restart CI here
