### ISSUE TITLE
Loading dask.distribute.Client fails with 2022.12.0

### ISSUE THREAD

**Issue by habi** [dask/dask#9720]
I have a project that uses an environment.yaml file, in which I load `dask`.
I am (currently) not pinning version numbers.

I've generated the conda environment on a new machine today and do this below in a Jupyter notebook.

```python
import dask
from dask.distributed import Client
print(dask.__version__)
client = Client()
````
prints "2022.12.0" and fails with "AttributeError: 'Nanny' object has no attribute 'add_done_callback'"

The same code on a machine on which I've installed the environment a while ago prints "2022.05.0" and produces a Client/LocalCluster where I can connect to with [`dask-labextension`](https//pypi.org/project/dasklabextension/).

**Comment by jrbourbeau** [comment]
Thanks for reporting @habi. What version of Python are you using? FWIW I've seen that error before when using Pyhon 3.11, which Dask doesn't currently support (xref https://github.com/dask/dask/issues/9691)

**Comment by habi** [comment]
Indeed, the fresh install on that machine installed Python 3.11.0, too.

Adding `python=3.10` to my environment.yaml file and recreating the conda environment works as expected, e.g. I can create a Client/LocalCluster with dask version "2022.12.0".

As I'm not very proficient with working with environment files, it it customary to pin the 'current' versions of the imports?

**Comment by phobson** [comment]
@habi the specificity with which you're pinning something depends on your use case and personal preference. At any rate, I personally feel that one *should* always pin python version.

**Comment by jrbourbeau** [comment]
Great, thanks for the feedback @habi -- for now I'd stick with `python<3.11`. I'm going to close this as a duplicate of https://github.com/dask/dask/issues/9691. We're currently working on Python 3.11 support and hope to have it released soon.
