### ISSUE TITLE
Documentation on how to set an s3 profile

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#9837]
From https://docs.dask.org/en/stable/how-to/connect-to-remote-data.html:

> The following parameters may be passed to s3fs using storage_options:
> [...]
> kwargs: Other parameters are passed to the [boto3 Session](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html) object, such as profile_name, to pick one of the authentication sections from the configuration files referred to above (see [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#shared-credentials-file))

However, this fails:
```python
dd.read_parquet(
    "s3://coiled-datasets/prefect-dask/nyc-uber-lyft/processed_data.parquet",
    storage_options={"kwargs": {"profile_name": "oss"}},
)

TypeError: AioSession.__init__() got an unexpected keyword argument 'kwargs'
```
This instead works:
```python
dd.read_parquet(
    "s3://coiled-datasets/prefect-dask/nyc-uber-lyft/processed_data.parquet",
    storage_options={"profile": "oss"},
)
```

However, the above is only fine as long as I run locally. If I connect to a Coiled cluster, it fails as soon as I try computing the dataframe, stating that the oss profile does not exist.
At the moment of writing, I could not find a clean solution.

**Workaround:** rename the `[oss]` profile to `[default]` in `~/.aws/credentials` and don't pass any parameters in Python.
I *think* that this causes the initial `read_parquet` call - which runs locally - to read the `role_arn` from my credentials, and then when the chunks are loaded remotely on the Coiled cluster there's *a different role_arn* that has been pre-set there?

**Comment by jrbourbeau** [comment]
Thanks @crusaderky. cc @martindurant for thoughts 

> Workaround

FWIW I've also found that setting the `AWS_PROFILE="oss"` environment variable also works

**Comment by martindurant** [comment]
The s3fs instance should be recreated from the arguments passed independently on the workers and the client - no dereferencing auth locally and sending that. That suggest that, if the same creds file exists in both places, the arguemt is not being forwarded correctly. In the case of read_parquet, I think we do not serialise the s3fs instance itself (which stores exactly the arguments used to create it) but send the "stoage_options" along in the graph.

That piece of documntation is clearly out of data, since s3fs uses (aio)botocore, not boto3, which accounts for profile_name->profile.
