### PR TITLE
Update `ga-yaml-parser` step in gpuCI updating workflow 

### PR DESCRIPTION
**Pull request by charlesbluca**
Looks like the auto-bump of `ga-yaml-parser` in https://github.com/dask/dask/pull/9553 changed the behavior of the action, making it so we haven't been running the gpuCI updating workflow in a while; this PR makes modifications that should unblock it.

- [ ] Closes #xxxx
- [ ] Tests added / passed
- [ ] Passes `pre-commit run --all-files`

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks for fixing @charlesbluca! 

Unrelated to the changes here, but I see we're getting the following failure in gpuCI:

```python
FAILED dask/dataframe/io/tests/test_io.py::test_from_dict_backends[cudf] - TypeError: from_dict() got an unexpected keyword argument 'constructor'
```

cc @rjzamora @galipremsagar for visibility. We're planning to release `dask` soon. Is this failure problematic for that? 

EDIT: my guess is "no" as it looks like this is an issue on the `cudf` side of things

**Comment by charlesbluca** [comment]
Yeah, I recently noticed that the Dask gpuCI images hadn't been rebuilt in a while and just resolved the failures in https://github.com/rapidsai/dask-build-environment/pull/54, so we might see some failures crop up in Dask/Distributed that weren't caught over the past few days

**Comment by jrbourbeau** [comment]
Are both the `dask` and `distributed` `main` branches now in a state where they're using rebuilt images?
