### ISSUE TITLE
read_csv broken on HDFS with Dask 2.2.0

### ISSUE THREAD

**Issue by AlexisMignon** [dask/dask#5285]
The following code (the last part) fails with Dask 2.2.0 while reading on HDFS:

```python
import dask.dataframe as dd


print("Read locally...")
df = dd.read_csv(
    "./test_file.csv",
)
print(df)
print(df.compute())
print(len(df))

print("\nRead on HDFS...")
df = dd.read_csv("hdfs://<path>/test_file.csv")
print(df)  # Columns are correctly read by npartitions=0
print(df.compute())  # Empty
print(len(df))  # Error
```
```
Read locally...
Dask DataFrame Structure:
                    A       B
npartitions=1                
               object  object
                  ...     ...
Dask Name: from-delayed, 3 tasks
   A  B
0  a  b
1  c  d
2  e  f
3

Read on HDFS...
Dask DataFrame Structure:
                    A       B
npartitions=0                
               object  object
Dask Name: from-delayed, 0 tasks
()
Traceback (most recent call last):
  File "test_csv.py", line 16, in <module>
    print(len(df)) # Error
TypeError: 'numpy.float64' object cannot be interpreted as an integer
AttributeError: 'HadoopFileSystem' object has no attribute 'close'
Exception ignored in: 'pyarrow.lib.HadoopFileSystem.__dealloc__'
AttributeError: 'HadoopFileSystem' object has no attribute 'close'
```

Tested with `dask==2.2.0 pandas==0.25 pyarrow=0.14`
as well as `dask==2.2.0 pandas==0.24.2 pyarrow=0.13`

The same code works with `dask==2.1.0 pandas==0.24.2 pyarrow=0.14` (with some error logs from arrow).

Interestingly, the header of the csv file is correctly read but it is reported as empty.

The test file was:

```csv
A,B
a,b
c,d
e,f
```

**Comment by TomAugspurger** [comment]
What version of fsspec when using dask 2.2.0?

Do you see a difference between what you're doing and our `dask/bytes/tests/test_hdfs.py::test_read_csv`?

**Comment by AlexisMignon** [comment]
Using ffspec==0.4.1

The only difference I see is that I have a server address in my url.

Like 
```
url = "hdfs://server-name/path/to/file.csv"
```

**Comment by TomAugspurger** [comment]
Can you try with fsspec master? It's a bit of a shot in the dark, but maybe it's been fixed recently.

**Comment by TomAugspurger** [comment]
https://github.com/intake/filesystem_spec

**Comment by AlexisMignon** [comment]
Same problem. I also had to edit the `_version.py` file of fsspec because the '<' comparison between `LooseVersion("0+unknown")` and `LooseVersino("0.3.3")`

**Comment by TomAugspurger** [comment]
Thanks for trying. cc @martindurant if you have any guesses.

@AlexisMignon you might try your exact test file in our docker image we use for testing HDFS: https://github.com/dask/dask/blob/master/continuous_integration/hdfs/README.md

**Comment by martindurant** [comment]
> "hdfs://<path>/test_file.csv"

hdfs paths start with "/", so, unfortunately, you need to use "hdfs:///<path>/test_file.csv" here (note the tripple slash), which is equivalent to "hdfs://<server>/<path>/test_file.csv", but with the server assumed.

**Comment by martindurant** [comment]
You *could* submit a issue or PR to the HDFS implementation in fsspec to prepend any path passed with a "/", that would be reasonable.

**Comment by AlexisMignon** [comment]
Any change between 2.1.0 and 2.2.0 that would explain this ? Because it works with 2.1.0.

**Comment by martindurant** [comment]
Yes, the complete file-handling interface was refactored. From my explanation above, this feels like the correct behaviour, although as I say, it could be reasonable to change https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L160 to ensure paths start with the `root_marker`, or to override this method specifically for the HDFS case.

**Comment by AlexisMignon** [comment]
For information I have added a property to my core-site.xml to set the default server:

 ```xml
<configuration>
<property>
<name>fs.default.name</name>
<value>hdfs://myserver/</value>
</property>
</configuration>
```

I can now use the url without the server name and got the same error

**Comment by martindurant** [comment]
? You were already using a URL without a server, no?

**Comment by AlexisMignon** [comment]
I think I've found the root of the problem.

https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/hdfs.py#L101

If I add 'info' to the list of properties to be used in `pahdfs`, it seems to work.

For informations I tried:

```python
fs, token, paths = get_fs_token_paths(myurl)
fs.info(paths[0])["size"]
```
It returns 0 in my case and returns a non zero value if I had "info" in the list of attributes coming from pahdfs.

**Comment by martindurant** [comment]
Hm, interesting. Please make the change in fsspec as a PR, and create a test in dask's hdfs test module, marked with xfail for the current version of fsspec or earlier.

**Comment by martindurant** [comment]
(I can do these too, but maybe slower than you)

**Comment by AlexisMignon** [comment]
I've made the changes in fsspec and sent a pull request but may not have time anymore to add the tests.

**Comment by jakirkham** [comment]
@AlexisMignon, is there anything else still needed for this issue? Appears your intake PR got merged 🙂

**Comment by AlexisMignon** [comment]
Basically, imho, there should be some investigations done to understand why the actual tests were not triggered. As I understand it the, the effect of the bug was that it was returning a size 0 for my test file.

**Comment by AlexisMignon** [comment]
I've found out that the result of:

```python
hdfs = pyarrow.hdfs.connect(host="myserver", port=xxxx)
hdfs.ls("/path/to/file")
```
is different when done with my actual hdfs server and what happens in the test docker.

In my case, file paths are prepended with protocol information while it is not the case in the test docker. This has the consequence to fail in the base class info method when checking path equality:
 https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L496

**Comment by TomAugspurger** [comment]
Does the test image need to be updated to use fsspec?

**Comment by martindurant** [comment]
Dask HDFS tests run against latest Dask, and require fsspec, which is installed [here](https://github.com/dask/dask/pull/5130). The image was rebuilt at [that time](https://hub.docker.com/r/daskdev/dask-hdfs-testing) and runs with pyarrow 0.14.1.

Fixed by https://github.com/intake/filesystem_spec/pull/109

**Comment by martindurant** [comment]
> the fact the hdfs file system is on localhost in the docker...

Specifically, that it was the *default* server. If you say `server='localhost'`, you see long-form paths.
