### ISSUE TITLE
da.to_zarr 2026.1.2 not backwards compatible with dask<2025.12.0 with zarr_format keyword arg and component

### ISSUE THREAD

**Issue by joshua-gould** [dask/dask#12265]
```python
import dask.array as da

# Group.create_array() got an unexpected keyword argument 'zarr_format'
# works with dask<2025.12.0
# fails with 2026.1.2
da.to_zarr(
    arr=da.random.random((2, 2)),
    url="test1.zarr",
    zarr_format=2,
    component="0",
)

# works with dask<2025.12.0 and 2026.1.2
da.to_zarr(
    arr=da.random.random((2, 2)),
    url="test2.zarr",
    zarr_format=2,
)
```

**Environment**:

- Dask version: 2026.1.2
- Install method: pip

**Comment by joshua-gould** [comment]
Not that dask==2026.1.1 is also not backwards compatible with  dask<2025.12.0-code runs but zarr_format parameter is ignored

**Comment by abslock128w** [comment]
Hey I'd like to have a look at this...

**Comment by TomAugspurger** [comment]
cc @melonora

**Comment by melonora** [comment]
The reason here is the zarr API, `zarr.create` is getting deprecated and now `Group.create_array` is used which does not have the `zarr_format` argument. There is no equivalent, unless we switch to `zarr.create_array` instead. which is what `Group.create_array` is lightly wrapping.
