### PR TITLE
fix: zarr.create_array for better backward compatibility

### LINKED ISSUE #12265: da.to_zarr 2026.1.2 not backwards compatible with dask<2025.12.0 with zarr_format keyword arg and component
```python
import dask.array as da

# Group.create_array() got an unexpected keyword argument 'zarr_format'
# works with dask<2025.12.0
# fails with 2026.1.2
da.to_zarr(
    arr=da.random.random((2, 2)),
    url="test1.zarr",
    zarr_format=2,
    component="0",
)

# works with dask<2025.12.0 and 2026.1.2
da.to_zarr(
    arr=da.random.random((2, 2)),
    url="test2.zarr",
    zarr_format=2,
)
```

**Environment**:

- Dask version: 2026.1.2
- Install method: pip

### PR DESCRIPTION
**Pull request by melonora**
- [x] Closes #12265
- [x] Tests added / passed
- [x] Passes `pre-commit run --all-files`

Minor adjustment to allow or better backward compatibility. This PR solely uses `zarr.create_array` where previously if `component` or `name` was defined, `Group.create_array` was used.

cc: @joshua-gould, @TomAugspurger

### CODE REVIEW

**Comment by melonora** [comment]
@jacobtomlinson @TomAugspurger When one of you has time, could you please have a look?:)

**Comment by TomAugspurger** [comment]
Thanks @melonora

**Comment by melonora** [comment]
No problem! sorry for yet another PR but I did not know at first `group.create_array` does not respect the zarr_format of the store.
