### ISSUE TITLE
Issue with Dask Distributed

### ISSUE THREAD

**Issue by timhdesilva** [dask/dask#7693]
Hi,

I'm having an issue with Dask Distributed. I'm running Python 3.8.10. When I run the following code, I have no issues.

``from dask import dataframe as dd``
``from dask.diagnostics import ProgressBar``
``data1 = dd.read_csv('data1.csv')``
``data2 = dd.read_csv('data2.csv')``
``data = dd.concat([data1, data2], ignore_index = True).compute()``

However, if I try to open a client before running the above code by using the following code
``from dask.distributed import Client; client = Client(); client
``
I get the following error: AttributeError: 'HighLevelGraph' object has no attribute '__dask_distributed_pack__'.

Any ideas here?

Thanks!

**Comment by quasiben** [comment]
Most likely you have an older version of dask and distributed.  Can you upgrade to the latest ? `2021.05.0` for both

**Comment by timhdesilva** [comment]
Thanks, I will definitely try that. Is there a particular way you'd like me to install these updates?

**Comment by jrbourbeau** [comment]
Either `pip install dask==2021.5.0 distributed==2021.5.0` or `conda install dask=2021.5.0 distributed=2021.5.0` depending on whether you use `pip` or `conda` to manage your local environments

**Comment by timhdesilva** [comment]
Great that works now, thank you. I have to work with versions 2021.2.0 because I'm using dask-sql, but things work now now that dask and distributed are on the same version.

One other follow-up question since I'm a total dask noob: what's the best way to interface with the dask client? I currently start the client in my .py file and then search for (http://localhost:8787/status) in my browser, but suspect there's a better way to do this. For reference, I use Python through Spyder 4.0. 

Thanks very much for your help everyone!

**Comment by jrbourbeau** [comment]
Glad to hear things are working now.

The `Client` also has it's own API (xref https://distributed.dask.org/en/latest/api.html) you can use. Though it sounds like maybe you're most interested in accessing the diagnostics dashboard? If so, then navigating to `client.dashboard_link` (which is http://localhost:8787/status by default when running a local Dask cluster) is how one accesses the dashboard

**Comment by jrbourbeau** [comment]
Closing as the original `AttributeError` has been resolved. Let us know if you run into other issues @timhdesilva

**Comment by timhdesilva** [comment]
Great, thank you for all your help!
