### ISSUE TITLE
Pandas 0.19.0

### ISSUE THREAD

**Issue by jmbertoncelli** [dask/dask#1615]
import dask.bag as db
import dask.dataframe as dd
from dask.cache import Cache
import dask as da
import numpy as np
from dask.diagnostics import ProgressBar
from dask.dot import dot_graph

create this error -->  ImportError: cannot import name local

works well with pandas 0.18.1

**Comment by mrocklin** [comment]
Some of these issues are handled in https://github.com/dask/dask/pull/1540

**Comment by jcrist** [comment]
Pandas 0.19.0 issues have been fixed by #1540. Closing.
