### PR TITLE
Fix meta computation for some reduction functions

### LINKED ISSUE #5029: sum() got an unexpected keyword argument 'keepdims'
I'm not sure if this is related to #4311 because in my case it only occurs using Dask.

Also, before, I was on Dask 1.2.0 and this error was inexistent:

- Dask 2.0.0+11.g7f26af69
- Pandas 0.24.2
- NumPy 1.16.4

```python
import pandas as pd
import dask.dataframe as dd
from dask.array import stats as dstats
from scipy import stats as sstats

s = pd.Series(list(range(1,10000)), name='series', dtype=float)
sd = dd.from_pandas(s, npartitions=2)

sstats.moment(s, 2, 0)
# 8331666.666666667

sstats.moment(sd, 2, 0)
# 8331666.666666667

dstats.moment(sd, 2, 0)
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-5-200bbf2f1719> in <module>
      1 
      2 
----> 3 dstats.moment(sd, 2, 0)

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/stats.py in moment(a, moment, axis, nan_policy)
    364             "`nan_policy` other than 'propagate' " "have not been implemented."
    365         )
--> 366     return da.moment(a, moment, axis=axis)
    367 
    368 

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/reductions.py in moment(a, order, axis, dtype, keepdims, ddof, split_every, out)
    740         out=out,
    741         concatenate=False,
--> 742         combine=partial(moment_combine, order=order),
    743     )
    744 

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/reductions.py in reduction(x, chunk, aggregate, axis, keepdims, dtype, split_every, combine, name, out, concatenate, output_size, meta)
    156     # The dtype of `tmp` doesn't actually matter, and may be incorrect.
    157     tmp = blockwise(
--> 158         chunk, inds, x, inds, axis=axis, keepdims=True, dtype=dtype or float
    159     )
    160     tmp._chunks = tuple(

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/blockwise.py in blockwise(func, out_ind, name, token, dtype, adjust_chunks, new_axes, align_arrays, concatenate, meta, *args, **kwargs)
    231         from .utils import compute_meta
    232 
--> 233         meta = compute_meta(func, dtype, *args[::2], **kwargs)
    234     if meta is not None:
    235         return Array(graph, out, chunks, meta=meta)

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/utils.py in compute_meta(func, _dtype, *args, **kwargs)
    120     else:
    121         try:
--> 122             meta = func(*args_meta, **kwargs_meta)
    123         except TypeError as e:
    124             if (

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/dask/array/reductions.py in moment_chunk(A, order, sum, numel, dtype, meta, **kwargs)
    624 
    625     n = n.astype(np.int64)
--> 626     total = sum(A, dtype=dtype, **kwargs)
    627     with np.errstate(divide="ignore", invalid="ignore"):
    628         u = total / n

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims, initial)
   2074 
   2075     return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
-> 2076                           initial=initial)
   2077 
   2078 

~/anaconda/envs/tarsierenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     80             # support a dtype.
     81             if dtype is not None:
---> 82                 return reduction(axis=axis, dtype=dtype, out=out, **passkwargs)
     83             else:
     84                 return reduction(axis=axis, out=out, **passkwargs)

TypeError: sum() got an unexpected keyword argument 'keepdims'
```

Any ideas what the problem may be?

### LINKED ISSUE #5049: da.mean crashing with numpy ndarray as input
Hi,

The following code crashes when run interactively in a fresh virtualenv:
```python
import numpy as np
import dask.array as da
arr = np.array([0.28588], dtype=np.float32)
da.mean(arr)
```

The traceback says:
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a001673/daskbug/lib/python3.6/site-packages/dask/array/core.py", line 1114, in __repr__
    self.dtype,
  File "/home/a001673/daskbug/lib/python3.6/site-packages/dask/array/core.py", line 1044, in dtype
    return self._meta.dtype
AttributeError: 'dict' object has no attribute 'dtype'
```

Versions tested on:
 * numpy 1.16.4
 * dask 2.0.0
 * toolz 0.9.0
 * python 3.6.4 and 3.7.3

Works when installing dask 1.2.2 instead

### PR DESCRIPTION
**Pull request by pentschev**
Fixes #5029, fixes #5049.

### CODE REVIEW

**Comment by pentschev** [comment]
@mrocklin I couldn't find a better way to add a test for this issue, or a way to reproduce this on dask array alone. Suggestions appreciated. :)

**Comment by pentschev** [comment]
I see that AppVeyor's build fails due to the recursion solved in #5048. But I'm not exactly sure what is the cause of the Travis failure, any ideas @mrocklin, @TomAugspurger?

**Comment by mrocklin** [comment]
I think that @TomAugspurger is working on this now.

**Comment by pentschev** [comment]
Alright, let's wait then. Thanks for the heads up!

**Comment by TomAugspurger** [comment]
I solved those ones yesterday. Now master should be passing (but I've noticed a few flaky test). @pentschev I merged master and pushed to see.

**Comment by TomAugspurger** [comment]
Saw one of the random appveyor problem (fatal stack overflow in the array tests). Restarted.

**Comment by pentschev** [comment]
The AppVeyor stack overflow issue in this PR should be solved by #5048, but it seems like that one is failing too.

**Comment by quasiben** [comment]
@TomAugspurger can you restart the AppVeyor CI ?  I don't have access

**Comment by TomAugspurger** [comment]
Done.

I poked around a bit, but didn't see a way to give you permission on AppVeyor @quasiben.

**Comment by jrbourbeau** [comment]
I sent @quasiben an invitation to the `dask-dev` team, so he should now have permissions on AppVeyor (let me know if this is not the case)

**Comment by pentschev** [comment]
Could we trigger the build here again? Last couple of times it failed due to random CI issues, seems like it's good again in other builds though.

**Comment by jrbourbeau** [comment]
Done

**Comment by pentschev** [comment]
Thanks @jrbourbeau, it failed again the same way, probably missing something from upstream. I merged it now, let's see.

**Comment by pentschev** [comment]
Hmm, now there are some s3 tests failing that don't seem related to this PR. Is that known @jrbourbeau @TomAugspurger?

**Comment by jrbourbeau** [comment]
I don't think this is a previously known issue. Running `pytest -sv dask/bytes/tests/test_s3.py` passes for me locally when using `s3fs==0.2.2` but not with the latest `s3fs==0.3.0` release

Any thoughts on this @martindurant?

**Comment by martindurant** [comment]
s3fs will work following https://github.com/dask/dask/pull/5064

**Comment by pentschev** [comment]
Thanks @martindurant, will keep an eye on that and merge it here when it gets into upstream.

**Comment by pentschev** [comment]
Now Travis passed, but there's now 31 errors in AppVeyor. Are those related to #5104?

**Comment by TomAugspurger** [comment]
Sorry @pentschev, at least some of those failures are from pandas. I dropped the ball on getting dask.dataframe ready for 0.25. https://github.com/dask/dask/pull/5056 has the fixes.

**Comment by pentschev** [comment]
No worries @TomAugspurger, I see #5056 should be green soon! :)

**Comment by pentschev** [comment]
@TomAugspurger the `test_temporary_directory` test is still failing. Was that supposed to be fixed in #5056 too?

**Comment by TomAugspurger** [comment]
> Was that supposed to be fixed in #5056 too?

Nope, I haven't figured that one out yet. I'd recommend ignoring it for now.

**Comment by pentschev** [comment]
> Nope, I haven't figured that one out yet. I'd recommend ignoring it for now.

Alright then!

@mrocklin @TomAugspurger can we merge this PR? Anybody would like to review it? Fixing #5029, #5049.

**Comment by pentschev** [comment]
@TomAugspurger thanks for checking. I don't have merging permissions, could you do it in a couple hours if we don't hear anything?

File: dask/array/utils.py [hunk 1]
```diff
@@ -119,6 +119,9 @@ def compute_meta(func, _dtype, *args, **kwargs):
         meta = func(*args_meta)
     else:
         try:
+            # some reduction functions need to know they are computing meta
+            if has_keyword(func, "computing_meta"):
+                kwargs_meta["computing_meta"] = True
```
Comment (jrbourbeau) [inline dask/array/utils.py]: Are there cases where a function with a `computing_meta` parameter would ever be called with `computing_meta=False`? If not, could we get rid of all `if computing_meta:` checks in functions with a `computing_meta=` keyword argument?

Comment (pentschev) [reply dask/array/utils.py]: `computing_meta=False` is the default, we only set it to `True` when we are computing a `meta` reduction. Not sure if this is what you asked, but this is just for those functions to know that the data is actually a `meta` array.

Comment (jrbourbeau) [reply dask/array/utils.py]: I guess my question is why are we handling the setting of `computing_meta` this way (based on the existence of the `computing_meta` keyword) as opposed to specifying `computing_meta=True` when a `meta` reduction is being computed?

For example, in this code block:

https://github.com/dask/dask/blob/842d96b7854371b435092a64812c1a282c0e1d51/dask/array/reductions.py#L166-L168

IIUC the value of the `computing_meta` parameter in like 167 doesn't seem to matter as the behavior of the `compute_meta` function is dictated by whether or not `chunk` has a `computing_meta` keyword, not the actual value of `computing_meta` being passed to the `compute_meta` function.

Comment (pentschev) [reply dask/array/utils.py]: I get it now. So `compute_meta` is a general-purpose function, that should be usable with any array function, thus, it can, for example, be used with `np.sum`, that doesn't have a `computing_meta` argument, that's why we need to test for that first ensuring we only set it for those reduction functions that need to know they are computing `meta`.

Comment (jrbourbeau) [reply dask/array/utils.py]: Gotcha, thanks for the clarification. Then is the `try` branch specifying `computing_meta=True` necessary here?

https://github.com/dask/dask/blob/842d96b7854371b435092a64812c1a282c0e1d51/dask/array/reductions.py#L165-L174

If not, I think it's best to remove it

Comment (pentschev) [reply dask/array/utils.py]: It is necessary. Not all reduction functions take `computing_meta`, the ones that require that are mostly those that would return/take a `dict` instead of an array. The remaining ones maintain the NumPy API (`chunk.sum`, `chunk.min`, etc.).

Comment (jrbourbeau) [reply dask/array/utils.py]: I see, the `try:` is for reduction functions which support `computing_meta` and the `except TypeError` is for all functions that don't (like `chunk.sum`). Thanks for the explanation, not sure why that wasn't clear to me before

**Comment by jrbourbeau** [comment]
Thanks @pentschev!

File: dask/array/utils.py (hunk 1 above)
Comment (pentschev) [reply dask/array/utils.py]: This part of the code is particularly complicated, it was probably the most difficult one to get right when implementing `_meta`, so I can definitely understand why that isn't clear. :)

**Comment by pentschev** [comment]
Thanks for reviewing and merging @TomAugspurger and @jrbourbeau!
