### PR TITLE
Normalize Xarray datasets to Dask arrays

### LINKED ISSUE #4532: Xarray handling regression in 1.1.2
Since dask 1.1.2, this crashes:

```python
import xarray as xr                                                                             
import dask.array as da                                                                         
da.mean(xr.DataArray([1, 2, 3.0])).compute()
```
The error raised:
`TypeError: nansum() got an unexpected keyword argument 'keepdims'`

I looks like a regression to me, but maybe I'm missing something ?

Works fine in 1.1.1

Relevant packages:
dask 1.1.2
xarray 0.11.3
numpy 1.16.2

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #4532

- [ ] Tests added / passed
- [ ] Passes `flake8 dask`

cc @mraspaud @shoyer if you have time to take a look at this I would appreciate it.

### CODE REVIEW

File: dask/array/tests/test_xarray.py [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+import dask.array as da
+from ..utils import assert_eq
+
+xr = pytest.importorskip('xarray')
+
+
+def test_xarray():
+    y = da.mean(xr.DataArray([1, 2, 3.0]))
+
+    assert_eq(y, y)
```
Comment (shoyer) [inline dask/array/tests/test_xarray.py]: does this verify that the type of the result is a dask array? `assert isinstance(y, da.Array)` might be a more direct way to do this.

Comment (mrocklin) [reply dask/array/tests/test_xarray.py]: Well, I could imagine future behavior being that the result here is an Xarray thing rather than a Dask thing.  I actually don't care too much about the output, as long as it computes and is self-consistent.

**Comment by jcrist** [comment]
LGTM, merging.
